#!/usr/bin/env node
/**
 * content/*.md -> index.html (shell) + manifest.json (nav metadata)
 *
 * No question or answer text is emitted into either file. The page fetches and
 * renders content/*.md at runtime, so the Markdown is the only place any
 * question, answer, follow-up or code sample exists.
 *
 * manifest.json carries nav metadata only — slug, order, number, group, title,
 * status, file — which is what the sidebar, progress bar and pagers need.
 */
const fs = require("fs");
const path = require("path");
const { loadSections } = require("./lib.js");

const ROOT = path.join(__dirname, "..");

function buildManifest(sections) {
  return sections.map((s) => ({
    slug: s.slug,
    order: s.order,
    number: s.number,
    group: s.group,
    title: s.title,
    status: s.status,
    file: `content/${String(s.order).padStart(2, "0")}-${s.slug}.md`,
    questions: s.questions.length, // a count, not the content
  }));
}

function shell(css, js) {
  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Interview Prep</title>
    <!--
      GENERATED by scripts/build.js — do not edit.
      This file deliberately contains no questions or answers; all content is
      loaded at runtime from content/*.md.
    -->
    <style>
${css.trimEnd()}
    </style>
  </head>
  <body>
    <header class="topbar">
      <button
        id="menubtn"
        class="menubtn"
        aria-label="Open topics"
        aria-expanded="false"
        aria-controls="sidebar"
      >
        <span class="bars"></span>
      </button>
      <span class="topbar-title" id="topbar-title">Interview Prep</span>
    </header>
    <div class="scrim" id="scrim" hidden></div>
    <div class="layout">
      <aside id="sidebar">
        <div class="brand">Interview Prep</div>
        <div class="progress">
          <div class="pbar"><div class="pfill" id="pfill"></div></div>
          <div class="pnum" id="pnum">&nbsp;</div>
        </div>
        <nav id="nav"></nav>
      </aside>
      <main id="main"></main>
    </div>
    <script>
${js.trimEnd()}
    </script>
  </body>
</html>
`;
}

function build() {
  const sections = loadSections();
  const css = fs.readFileSync(path.join(ROOT, "src/styles.css"), "utf8");
  const js = fs.readFileSync(path.join(ROOT, "src/app.js"), "utf8");

  const manifest = buildManifest(sections);
  fs.writeFileSync(
    path.join(ROOT, "manifest.json"),
    JSON.stringify(manifest, null, 2),
    "utf8",
  );
  fs.writeFileSync(path.join(ROOT, "index.html"), shell(css, js), "utf8");

  const done = manifest.filter((s) => s.status === "answered").length;
  const bytes = fs.statSync(path.join(ROOT, "index.html")).size;
  console.log(
    `built index.html (${(bytes / 1024).toFixed(1)} KB shell, no content) + ` +
      `manifest.json — ${manifest.length} sections, ${done} answered`,
  );
}

if (require.main === module) build();
module.exports = { build, buildManifest };
